[package]
name = "tower-etag-cache"
version = "0.1.0"
edition = "2021"

[features]
default = []
simple-cache-key = []
base64-blake3-body-etag = ["dep:base64", "dep:blake3"]
const-lru-provider = ["dep:const-lru", "dep:num-traits", "dep:tokio", "dep:tokio-util", "simple-cache-key", "base64-blake3-body-etag"]

[dependencies]
base64 = { version = "^0.21", optional = true }
blake3 = { version = "^1.0", optional = true }
const-lru = { version = "^0.2", optional = true }
http = "^0.2"
http-body = "^0.4"
pin-project = "^1.0"
num-traits = { version = "^0.2", optional = true }
time = "^0.3"
tokio = { version = "^1.0", features = ["sync"], optional = true }
tokio-util = { version = "^0.7", optional = true }
tower-service = "^0.3"
